apiVersion: apps/v1
kind: Deployment
metadata:
  name: albert-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: albert-app
  template:
    metadata:
      labels:
        app: albert-app
    spec:
      containers:
        - name: albert-app
          image: <AWS-ACCOUNT-ID>.dkr.ecr.<AWS-REGION>.amazonaws.com/albert-ecr-repository:latest # Replace with your 'AWS ACCOUNT ID' and 'AWS REGION'
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: regcred